language: java
jdk:
- openjdk8
services:
- docker

before_install:
  - docker pull openjdk:8-jdk-alpine

# Test & Build SpringBoot app
script:
  - ./gradlew build

# Create Docker image for our app and push it to Dockerhub repository
after_success:
  - export COMMIT=${TRAVIS_COMMIT::7}
  - export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH--$COMMIT"; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $DOCKER_USER/$IMAGE_NAME:$TAG
  - export TITLE="$IMAGE_NAME:$TAG is built properly and pushed to Dockerhub"
  - export TIMESTAMP=`date`
  - export GIT_LOG=`git log -1 --pretty=%B $COMMIT`
  - export TEXT="[build version] $TAG<br />[datetime] $TIMESTAMP<br />[changelog] $GIT_LOG<br />"


# Allow Travis to help deploy the app on Heroku
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app: docker-spring-boot-sample
  on:
    tags: false
    repo: "evelynsv/$IMAGE_NAME"
