FROM openjdk:8-jdk-alpine
VOLUME /tmp

ARG JAR_BASE_NAME=${JAR_BASE_NAME}
ARG BUILD_VERSION=${BUILD_VERSION}
ARG JAR_FILE=$JAR_BASE_NAME-$BUILD_VERSION.jar

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]

EXPOSE 8080